# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

RUST_MIN_VER="1.88.0"

inherit cargo desktop xdg

DESCRIPTION="Open-source AI-native terminal and development workspace"
HOMEPAGE="https://terax.app/ https://github.com/crynta/terax-ai"
SRC_URI="
	https://localhost/distfiles/${P}.tar.xz
	https://localhost/distfiles/${P}-vendor.tar.xz
	https://localhost/distfiles/${P}-node_modules.tar.xz
"

LICENSE="
	0BSD AFL-2.1 Apache-2.0 Apache-2.0-with-LLVM-exceptions BSD BSD-2
	Boost-1.0 CC0-1.0 CDLA-Permissive-2.0 ISC LGPL-2.1+ MIT MIT-0 MPL-2.0
	OFL-1.1 Unicode-3.0 Unlicense ZLIB
"
SLOT="0"
KEYWORDS="~amd64"
RESTRICT="mirror"

DEPEND="
	dev-libs/glib:2
	net-libs/libsoup:3.0
	net-libs/webkit-gtk:4.1
	sys-apps/dbus
	x11-libs/gtk+:3
"
RDEPEND="${DEPEND}"
BDEPEND="
	>=net-libs/nodejs-22.13.0
	virtual/pkgconfig
"

# This archive is generated by cargo vendor.  It must remain outside ${S},
# whose src-tauri/Cargo.toml is itself a workspace root.
ECARGO_VENDOR="${WORKDIR}/vendor"

PATCHES=( "${FILESDIR}/${P}-updater-timeout.patch" )

src_unpack() {
	cargo_src_unpack
	mv "${WORKDIR}/node_modules" "${S}/" || die "failed to place vendored node_modules"
}

src_configure() {
	cargo_src_configure \
		--manifest-path src-tauri/Cargo.toml \
		--features tauri/custom-protocol \
		--locked
}

src_compile() {
	./node_modules/.bin/tsc || die "TypeScript compilation failed"
	./node_modules/.bin/vite build || die "frontend build failed"

	cargo_src_compile
}

src_install() {
	exeinto /usr/libexec
	newexe "src-tauri/$(cargo_target_dir)/terax" terax-bin
	dobin "${FILESDIR}/terax"

	newicon -s 512 src-tauri/icons/icon.png app.crynta.terax.png
	make_desktop_entry --eapi9 terax \
		-a "%F" \
		-c "System;TerminalEmulator;Development;" \
		-C "AI-native terminal emulator and development workspace" \
		-d app.crynta.terax \
		-i app.crynta.terax \
		-n Terax

	dodoc README.md
}
